namespace: todoapp

serviceAccount:
  name: mysql-sa

replicaCount: 1

image:
  repository: mysql
  tag: "8.0"

resources:
  requests:
    memory: "256Mi"
    cpu: "150m"
  limits:
    memory: "256Mi"
    cpu: "150m"

pvc:
  requestStorage: 1Gi

affinity:
  key: app
  value: mysql

tolerations:
  key: app
  operator: Equal
  value: mysql
  effect: NoSchedule

secrets:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "tododb"
  MYSQL_USER: "todouser"
  MYSQL_PASSWORD: "todopassword"