apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.hostPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.requestStorage }}